version: 2.1
executors:
  ci-executor:
    docker:
      - image: REPLACE-ME-WITH-DOCKER-IMAGE
jobs:
  build:
    executor: ci-executor

    steps:
      - checkout

      - run:
          name: install dependencies
          command: bundle install

      - run:
          name: build the jekyll site
          command: REPLACE-ME-WITH-BUILD-COMMAND

      - run:
          name: notify build is finished
          command: echo "The build is finished!"
