version: 2.1
executors:
  ci-executor:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
jobs:
  build:
    executor: ci-executor

    steps:
      - checkout

      - run:
          name: install dependencies
          command: bundle install

      - run:
          name: build the jekyll site
          command: bundle exec jekyll build

      - run:
          name: notify build is finished
          command: echo "The build is finished!"
